### ISSUE TITLE
Wrong Median

### ISSUE THREAD

**Issue by AliSafari-IT** [mr-subroutine/meanmediancalc1#1]
Hello,
thanks for sharing your codes!

I think for calculating Median Value you should modify your if-else statements in [meanmediancalc1/MeanMedianCalculator1/Form1.cs](https://github.com/mr-subroutine/meanmediancalc1/blob/master/MeanMedianCalculator1/Form1.cs).

if (medianValue == 0)
            {
                medianValue = convertedArray.Length / 2;
                int firstValue = convertedArray[medianValue];
                int secondValue = convertedArray[medianValue + 1];
                int newMedianValue = (firstValue + secondValue) / 2;
                MessageBox.Show("The median of sorted values is: " + newMedianValue);
            }
else{
int medianValue = convertedArray.Length / 2;
                medianValue = convertedArray[medianValue+**1**];
                MessageBox.Show("The median of sorted values is: " + medianValue);
}

**Comment by mr-subroutine** [comment]
Just messing around with C# in the early days.  I'll rewrite a better one in the future if I get to it.
